---
- hosts: webservers 
  become: True
  tasks:
    - name: install apache2
      apt:
        name: apache2
        update_cache: yes
        state: present
    - name: install php modules
      apt:
        name:
          - php 
          - libapache2-mod-php 
          - php-mysql 
...
